import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar/Navbar";
import Card from '../components/Card/Card';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Tourism App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
  <div className='flex flex-row'>
  <Image src="/Mapsicle.png" height={100} width={1000} />

  <Card/>
  </div>
       
        
        </div>
      
  )
}
